# Generated by Django 4.1.7 on 2023-04-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='email',
        ),
    ]
