# Generated by Django 4.1.7 on 2023-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0007_alter_task_due_date_alter_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
