# Generated by Django 4.2 on 2023-05-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0008_alter_task_due_date_alter_task_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='time',
            new_name='due_time',
        ),
    ]
